name: Publish Docker image
on: [push]

jobs:
  push_to_registry:
    name: Expense Tracker Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Check out GitHub repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build image and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: nomanrns/expense-tracker:latest-${{ steps.extract_branch.outputs.branch }}
      - name: Copy Build Script via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "scripts/docker-deploy.sh"
          target: "/tmp"
      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        env:
          CONTAINER_NAME: "expense-tracker-${{ steps.extract_branch.outputs.branch }}"
          IMAGE_NAME: "nomanrns/expense-tracker:latest-${{ steps.extract_branch.outputs.branch }}"
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script_stop: true
          script: |
            chmod +x /tmp/docker-deploy.sh
            /tmp/docker-deploy.sh $CONTAINER_NAME $IMAGE_NAME
          envs: CONTAINER_NAME, IMAGE_NAME
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.WEBHOOK_URL }}
        uses: Ilshidur/action-discord@master
        with:
          args: "${{ github.job }} job of ${{ github.repository }}:${{ steps.extract_branch.outputs.branch }} has ${{ job.status }}"
