name: Publish Docker image
on: [push]

jobs:
  push_to_registry:
    name: Build and push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Check out GitHub repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build image and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: nomanrns/expense-tracker:latest-${{ steps.extract_branch.outputs.branch }}
      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        env:
          CONTAINER_NAME: "expense-tracker-${{ steps.extract_branch.outputs.branch }}"
          IMAGE_NAME: "nomanrns/expense-tracker:latest-${{ steps.extract_branch.outputs.branch }}"
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script_stop: true
          script: |
            docker stop $CONTAINER_NAME
            docker rm -f $CONTAINER_NAME
            docker run -d -p 3000:3000 --name $CONTAINER_NAME $IMAGE_NAME
          envs: CONTAINER_NAME, IMAGE_NAME
